SELECT
   TO_CHAR(EXTRACT(YEAR FROM i.INVOICEDATE)) || '-' || LPAD(TO_CHAR(EXTRACT(MONTH FROM i.INVOICEDATE)), 2, '0') AS YEAR_MONTH,
   c.CUSTOMERNAME,
   g.STOCKGROUPNAME,
   ROUND(AVG(h.QUANTITYONHAND), 2) AS AVG_QUANTITYONHAND
FROM
   WWI.STOCKITEMTRANSACTIONS r
JOIN
   WWI.CUSTOMERS c
ON
   r.CUSTOMERID = c.CUSTOMERID
JOIN
   WWI.STOCKITEMHOLDINGS h
ON
   r.STOCKITEMID = h.STOCKITEMID
JOIN
   WWI.STOCKITEMSTOCKGROUPS s
ON
   r.STOCKITEMID = s.STOCKITEMID
JOIN
   WWI.STOCKGROUPS g
ON
   s.STOCKGROUPID = g.STOCKGROUPID
JOIN
   WWI.INVOICES i
ON
   r.INVOICEID = i.INVOICEID
GROUP BY
   ROLLUP (
       TO_CHAR(EXTRACT(YEAR FROM i.INVOICEDATE)) || '-' || LPAD(TO_CHAR(EXTRACT(MONTH FROM i.INVOICEDATE)), 2, '0'),
       c.CUSTOMERNAME,
       g.STOCKGROUPNAME
   )
;