PROC SORT DATA = result;
    BY FullName;
RUN;
PROC DS2;
    DATA test_result /OVERWRITE=YES;
        DCL DOUBLE Total;
        RETAIN Total;
        KEEP FullName Total;
        METHOD run();
            SET result;
            BY FullName;
            IF FIRST.FullName THEN Total = 0;
            Total = Total + 1;
            IF LAST.FullName THEN OUTPUT;
        END;
    ENDDATA;
RUN;
QUIT;
PROC SORT DATA = test_result;
    BY DESCENDING Total;
RUN;
PROC PRINT DATA = work.test_result;
RUN;