SELECT
   p.FULLNAME,
   EXTRACT(YEAR FROM o.ORDERDATE) AS ORDER_YEAR,
   EXTRACT(MONTH FROM o.ORDERDATE) AS ORDER_MONTH,
   SUM(l.QUANTITY) AS Total_Quantity,
   SUM(SUM(l.QUANTITY)) OVER (PARTITION BY p.FULLNAME ORDER BY EXTRACT(YEAR FROM o.ORDERDATE), EXTRACT(MONTH FROM o.ORDERDATE)) AS Cumulative_Transactions
FROM
   WWI.ORDERLINES l
JOIN
   WWI.ORDERS o ON l.ORDERID = o.ORDERID
JOIN
   WWI.PEOPLE2 p ON o.SALESPERSONPERSONID = p.PERSONID
GROUP BY
   EXTRACT(YEAR FROM o.ORDERDATE),
   EXTRACT(MONTH FROM o.ORDERDATE),
   p.FULLNAME;