WITH RankedOrders AS (
   SELECT
       p.FULLNAME,
       p.EMAILADDRESS,
       EXTRACT(YEAR FROM o.ORDERDATE) AS ORDER_YEAR,
       EXTRACT(MONTH FROM o.ORDERDATE) AS ORDER_MONTH,
       SUM(l.UNITPRICE * l.QUANTITY) AS ORDER_AMOUNT,
       SUM((l.UNITPRICE * l.QUANTITY * l.TAXRATE) / 100) AS TAX_AMOUNT,
       ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM o.ORDERDATE) ORDER BY SUM(l.UNITPRICE * l.QUANTITY) DESC) AS RN
   FROM
       WWI.ORDERLINES l
   JOIN
       WWI.ORDERS o ON l.ORDERID = o.ORDERID
   JOIN
       WWI.PEOPLE2 p ON o.SALESPERSONPERSONID = p.PERSONID
   GROUP BY
       p.FULLNAME,
       p.EMAILADDRESS,
       EXTRACT(YEAR FROM o.ORDERDATE),
       EXTRACT(MONTH FROM o.ORDERDATE)
)
SELECT
   FULLNAME,
   EMAILADDRESS,
   ORDER_YEAR,
   ORDER_MONTH,
   ORDER_AMOUNT,
   TAX_AMOUNT
FROM
   RankedOrders
WHERE
   RN = 1 -- Można użyć aby zobaczyć tylko top 1 w każdym roku.
ORDER BY
   ORDER_YEAR, ORDER_MONTH;